package: googleplaces
version: "3.0.0-RC1"
author: "FriendsOfREDAXO"

page:
  title: "Google Places"
  perm: googleplaces[]
  pjax: true
  icon: rex-icon fa fa-map-marker
  subpages:
    place_detail:
      title: "translate:googleplaces_place_detail"
      icon: "fa fa-map-marker"
    review: 
      title: "translate:googleplaces_review"
      icon: "fa fa-star" 
    docs:
      icon: "rex-icon fa fa-question-circle"
      title: "translate:googleplaces_docs"
      pjax: false
      itemclass: pull-right
    config:
      icon: "rex-icon fa fa-cog"
      itemclass: "pull-right"
      title: "translate:googleplaces_config"
    sync:
      icon: "rex-icon fa fa-refresh"
      itemclass: "pull-right"
      title: "translate:googleplaces_sync"
    query:
      icon: "rex-icon fa fa-search"
      itemclass: "pull-right"
      title: "translate:googleplaces_query"

requires:
  php:
    version: '>8.1,<9'
  redaxo: ">=5.17"
  packages:
    yform: ">=4.0.0"
    yform_field: ">=2.9.0"

default_config:
  api_key: ""
