# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: googleplaces
version: '3.0.0-dev-2025-02-07'
author: 'FriendsOfREDAXO'

page:
  title: 'Google Places'
  perm: googleplaces[]
  pjax: true
  icon: rex-icon fa fa-map-marker
  subpages:
    place_detail: { title: 'translate:googleplaces_place_detail', icon: "fa fa-map-marker" }
    review: { title: 'translate:googleplaces_review', icon: "fa fa-star" }
    config: { title: 'translate:googleplaces_config' }
    docs:
      icon: 'rex-icon fa fa-question-circle'
      title: 'translate:googleplaces_docs'
      pjax: false
      itemclass: pull-right

requires:
    packages:
    redaxo: '>=5.10'

default_config:
  gmaps-location-id: ''
  gmaps-api-key: ''
