# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: googleplaces
version: '2.3.2'
author: 'FriendsOfREDAXO'

page:
  title: 'Google Places'
  perm: googleplaces[]
  pjax: true
  icon: rex-icon fa fa-map-marker
  subpages:
    review: { title: 'translate:googleplaces_reviews', icon: "fa fa-star" }
    place_detail: { title: 'translate:googleplaces_place_details', icon: "fa fa-info-circle" }
    config: { title: 'translate:googleplaces_config' }
    docs:
      icon: 'rex-icon fa fa-question-circle'
      title: 'translate:googleplaces_start'
      pjax: false
      itemclass: pull-right
      subpages:
        intro:
          title: 'translate:googleplaces_docs_intro'
          pjax: false
          subPath: README.md
        modules:
          title: 'translate:googleplaces_docs_modules'
          pjax: false
          subPath: docs/modules.md
        credits:
          title: 'translate:googleplaces_docs_credits'
          pjax: false
          subPath: docs/credits.md

requires:
    packages:
    redaxo: '>=5.10'

default_config:
  gmaps-location-id: ''
  gmaps-api-key: ''
